services:
  - type: web
    name: workforce-manager
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install; npm run build
    startCommand: npm run start
    staticPublishPath: ./dist/public
    routes:
      - type: rewrite
        source: /api/*
        destination: /api/$1
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_ST1xy8lAVqLF@ep-cool-bar-a4i0caol-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require
      - key: SESSION_SECRET
        value: sEsjSIwbtR2uJ8/4i7CKK7H4rouVp9YHVfKdpdoxtIeBZTxXPzfvVtwwK37jVOQaDd8984h5eAhO3Rg43tGIYA==
      - key: EMAIL_USER
        value: gestione.davittorino@gmail.com
      - key: EMAIL_APP_PASSWORD
        value: qzzi vhfh ljmp zvxc

databases:
  - name: workforce-db
    plan: free
    region: frankfurt 